---
title: "strings_and_factors"
author: "Sarah Haberlack"
date: "2023-11-01"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)

library(p8105.datasets)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Strings and regex

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff")

str_replace(string_vec, "jeff", "Jeff")


```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think")
## i want to detect the beginning of the line, then "i think"

str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "[Bb]ush")
## for this location, you can detect capital or lowercase B as long as it's followed by "ush"
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
## dot is a special signal in regular expressions that matches literally any other thing that exists in the string.

## if you want to match a dot specifically, and interpret it as a regular dot:

str_detect(string_vec, "7\\.11")

##because the slash itself is also a special signal, you need two slashes.
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```

## Factors

```{r}
factor_vec = factor(c("male", "male", "female", "female"))

## This will give me information about levels in alphabetical order

as.numeric(factor_vec)

## says realy underneath this, female is a 1 and male is a 2. the integer structure that underlies the factor variable that i have created.
```

what happens if i relevel...

```{r}
factor_vec = fct_relevel(factor_vec, "male") 

factor_vec

as.numeric(factor_vec)

```

most used fct_ commands: fct_relevel, fct_recode (lets you change a label), fct_reorder

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(url) |> 
  html_nodes(css = "table") |> 
  first() |>
  html_table() |> 
  slice(-1) |> 
  as_tibble()

#slice -1 is to remove the bottom row
```

```{r}
data_marj =
  table_marj |> 
  select(-contains("P value")) |> 
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) |> 
  separate(age_year, into = c("age", "year"), sep = "\\(") |> 
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c$]", ""),
    percent = as.numeric(percent) 
  ) |> 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))

# contains is doing something very similar to str_detect

# how to replace ) with absolutely nothing. str_trim might work too.

# i'm being specific about [a-c] because if i'm missing someting about how this dataset works, i want this code to break so that I can see that.
```

## NSDUH -- factors
```{r}
data_marj |> 
  filter(age == "12-17") |> 
  mutate(State = fct_relevel(State, "Texas", "Oklahoma")) |> 
  ggplot(aes(State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

# reordering instead of releveling
```{r}
data_marj |> 
  filter(age == "12-17") |> 
  mutate(State = fct_reorder(State, percent)) |> 
  ggplot(aes(State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# reording State by percent lowest to. highest. puts things in order of the median value.

#Utah has the lowest median percent in 2014-2015.
```

## Weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2023-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
weather_df |> 
  mutate(name = fct_reorder(name, tmax)) |> 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()
```

```{r}
weather_df |> 
  mutate(name = fct_reorder(name, tmax)) |> 
  lm(tmax ~ name, data = _)
```


